### ISSUE TITLE
HTTPServer library

### ISSUE THREAD

**Issue by buhaescuvlad** [google/universal-dash-transmuxer#1]
Hello and thanks for your contribution....but i need some directions here:
1. i cant find .xcodeproj for any of the projects above
2. i try to make my own project using the same files but i cannt find   "<HTTPServer.h>"  library/framework

Thanks,
     Vlad

**Comment by justsomeguy-google-com** [comment]
You will need to use gyp to build the Xcode projects.

https://code.google.com/p/gyp/

**Comment by buhaescuvlad** [comment]
Great,thanks
