### ISSUE TITLE
Support 16-byte IV

### ISSUE THREAD

**Issue by goalstudio** [google/universal-dash-transmuxer#13]
Current version of transmuxer only supports 8-byte IV that causes a problem for real VOD services that have all DASH+CENC content encoded with 16-byte IV. Content play fine on all platforms except iOS with Widevine CDM because they're using this transmuxer.

**Comment by SeawardT** [comment]
I will add this to our roadmap to get support added to the transmuxer. Thanks!

**Comment by Streebor** [comment]
@SeawardT Did you guys address this issue?

**Comment by SeawardT** [comment]
Yes this was resolved. It has been pushed as part of our iOS CDM already but has not been here to github yet. That is coming.

**Comment by joeyparrish** [comment]
The project is dead.  We apologize for any inconvenience.  Feel free to continue it in a fork if you wish.  See also a bit more detail in #19.
