### ISSUE TITLE
DASH to HLS doesn't handle multiple PSSH boxes

### ISSUE THREAD

**Issue by colde** [google/universal-dash-transmuxer#2]
When using this as part of the Widevine iOS libraries (and probably for other cases as well) the psshHandler is only called for the first PSSH box. This means that if the first box is an unsupported box for the platform, playback will fail as it will be impossible to setup the CDM components.

Either setting the PSSH handler should accept a UUID identifier for which keysystems to listen to, or it should at the very least call the handler for each of the keysystems present.

So most likely https://github.com/google/universal-dash-transmuxer/blob/master/library/dash_to_hls_api.cc#L223 needs to use FindDeepAll and then iterate over the contents.

**Comment by justsomeguy-google-com** [comment]
Loke,

You are correct  Do you have a CLA?

**Comment by colde** [comment]
@justsomeguy-google-com  I don't. I am from a Widevine licensee though, not sure if that covers it.

**Comment by justsomeguy-google-com** [comment]
It does not.  Please fill out a CLA

https://sites.google.com/a/google.com/ospo/creating/google-oss/accepting-contributions
https://cla.developers.google.com/about/google-individual
https://cla.developers.google.com/about/google-corporate

**Comment by colde** [comment]
That first link i think requires a google account. 

Actually, i just checked, we did submit a CLA for Xstream A/S to add some contribution to edash-packager. It was sent to cla-submission back in 2014.

**Comment by bobek** [comment]
:+1:

This problem is blocking as well. And iOS9 is coming and Classic cannot work with AirPlay :( Can we do anything for helping with this ticket?

**Comment by justsomeguy-google-com** [comment]
If someone has a test I can run, (content with a DRM URL) I can push a fix
pretty quick.

**Comment by bobek** [comment]
Awesome, you can use the following mpd: http://showmax.akamaized.net/u/3eec06ce-236b-4c17-b925-6fe787943420/5e51323e-1a1a-44e1-a2ae-f0d2d72a3dfc.ism/.mpd

**Comment by justsomeguy-google-com** [comment]
What should I use for the license url?

**Comment by bobek** [comment]
Not sure, why you need a license url. We will not give you license anyway :) I believe, that key is in getting .dash and parsing PSSH included.

**Comment by justsomeguy-google-com** [comment]
Antonin,

Right, don't need a license url, but I wanted to verify that once I fix
something you'd be getting a valid license.

Anyway, got the .mpd, but it appears to use a SegmentTeplate.  Can you give
me a URL for just the initialization segment?

**Comment by bobek** [comment]
Sure, let's take other video, so I don't need to dig for the initial chunk:

http://showmax.akamaized.net/u/9b021099-cc3b-4b19-8568-0d133c359181/fcada32c-ea71-423c-9d64-68b62d98bacd.ism/.mpd

http://showmax.akamaized.net/u/9b021099-cc3b-4b19-8568-0d133c359181/fcada32c-ea71-423c-9d64-68b62d98bacd.ism/dash/fcada32c-ea71-423c-9d64-68b62d98bacd-video=802000.dash

**Comment by colde** [comment]
Have this been fixed, or should i provide a sample?

**Comment by justsomeguy-google-com** [comment]
I have a patch coming this week that will fix it.

**Comment by SeawardT** [comment]
This was resolved. Please let me know if anyone is still experiencing this issue.
