### ISSUE TITLE
dash_to_hls_api.cc GetDuration() doesn't fall back to trex box

### ISSUE THREAD

**Issue by Uragawa** [google/universal-dash-transmuxer#3]
The duration of a sample should fall back to ```trex``` if it isn't specified in ```trun``` and a default isn't present in ```tfhd```. Writing the container like that apparently isn't recommended behaviour but it happens in practice.

**Comment by rbouqueau** [comment]
GPAC/MP4Box maintainer here. The technical explanation at https://github.com/gpac/gpac/issues/234#issuecomment-140026567

**Comment by justsomeguy-google-com** [comment]
I need a clear sample that shows this problem.

**Comment by justsomeguy-google-com** [comment]
I have a patch I'll upload later this week. It will check the trex if one exists and there is no duration in the trun or tfhd.

**Comment by Uragawa** [comment]
As far as I'm concerned this issue can be closed.

**Comment by joeyparrish** [comment]
From what I can tell, this was fixed at the same time as #4.  We can reopen if this is not the case.  Thanks, @Uragawa.
