### ISSUE TITLE
How to get the compiled library

### ISSUE THREAD

**Issue by salva84** [google/universal-dash-transmuxer#8]
Hi team,

we need to to run the cdm_reference_player_ios project with the new version of the library that is now published in github, this is, the changes you did on the universal-dash-transmuxer. Since we are not able to compile the github code for generating the oemcrypto_tfit2-eit_dev_dylib and oemcrypto_tfit2_dev_dylib_sim libraries we would need the compiled version, is it possible? (the current code has external references we cannot solve on our end)

Thanks!

**Comment by andyclarkson** [comment]
Hi guys, has anyone had a look at this would be amazing if we could get some guidance.

Thanks,
Andy

**Comment by Uragawa** [comment]
Hello,
You may need to get rid of ``DashToHLSResourceLoader`` for this to work (I did it with an older version that lacked that class; if you do get rid of it don't forget to disable HLS encryption when generating the manifests), but testing the updated UDT should be doable if you rename all of UDT's external symbols (basically the ``dash2hls`` namespace and the functions marked as ``extern "C"``) and change the code in cdm_reference_player_ios to reference the renamed symbols instead. AFAIK, the crypto side does not directly reference UDT.

**Comment by SeawardT** [comment]
We are still identifying how to best accomplish this. Our primary solution would be to have the iOS reference application interact directly with this repo, but it would need to be clear content and have no DRM involved.
