### ISSUE TITLE
MVHD and MDHD Parsing Errors

### ISSUE THREAD

**Issue by csloan-gmail** [google/universal-dash-transmuxer#9]
When these boxes have a version == 1 MdhdContents::Parse and MvhdContents::Parse parse the time scale member as 64-bits when it should be 32-bits.  Interestingly, the comments before these functions have the proper class definitions from ISO 14496-12 so it just looks like a duplicated typo.

I fixed these locally to get our content parsing properly but we need these changes in future player SDKs.  Can someone take a look?

Thanks,
Chris

**Comment by joeyparrish** [comment]
Thanks for the report.  We'll take a look and get back to you.

**Comment by joeyparrish** [comment]
Yes, it definitely looks like a typo.

**Comment by SeawardT** [comment]
Resolved on v3.0.4 branch. Please feel free to use that for now until we merge.
